#!/bin/bash
set -e

PROFILE_SCRIPT="/etc/profile.d/kernelmind_apex.sh"

if [ -f "${PROFILE_SCRIPT}" ]; then
    rm -f "${PROFILE_SCRIPT}"
fi

rm -f /etc/kernelmind/marvin_ros_control/config
rm -f /etc/kernelmind/marvin_teleop/config
